name: 'Terraform'
 
 #Run2

on: 
  workflow_dispatch:
  push:
    branches:
      - development
      - main

jobs:
  terraform-dev-plan:
    name: 'Terraform Plan - dev'

    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Echo Environment
        run: |
          echo "Hello Development"
    
  terraform-qa-plan:
    name: 'Terraform Plan - QA'
    needs: terraform-dev-plan

    runs-on: ubuntu-latest
    environment: qa

    steps:
      - name: Echo Environment
        run: |
          echo "Hello QA"

  terraform-production-plan:
    name: 'Terraform Plan - prod'
    needs: terraform-qa-plan

    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Echo Environment
        run: |
          echo "Hello Production"

